@startuml

!include dist/common.puml
!include dist/all.puml

title 1С:Enterprise icons for PlantUML

v8_Catalog(Каталог)
v8_Document(Документ)
v8_InfoRg(РегистрСведений)
v8_AccRg(РегистрНакопления)
v8_Enum(Перечисление)

v8_Role(Роль)
v8_CommonAttribute(ОбщийРеквизит)
v8_ExchangePlan(ПланОбмена)
v8_FilterCriteria(КритерийОтбора)
v8_EventSubscription(ПодпискаНаСобытие)
v8_ScheduledJob(РегламентноеЗадание)
v8_Bot(Бот)
v8_FunctionalOption(ФункциональнаяОпция)
v8_FunctionalOptionsParameters(ПараметрыФункциональныхОпций)
v8_DefinedType(ОпределяемыйТип)
v8_SettingsStorage(ХранилищеНастроек)
v8_CommonCommand(ОбщаяКоманда)
v8_CommandGroup(ГруппаКоманд)

v8_AccountingRg(РегистрБухгалтерии)
v8_BusinessProcess(БизнесПроцесс)
v8_CalculationRg(РегистрРасчета)
v8_ChartOfAccounts(ПланСчетов)
v8_ChartOfCalculationTypes(ПланВидовРасчета)
v8_ChartOfCharacteristicTypes(ПланВидовХарактеристик)
v8_CommonForm(ОбщаяФорма)
v8_CommonPicture(ОбщаяКартинка)
v8_Const(Константа)
v8_DataProcessor(Обработка)
v8_DocumentJournal(ЖурналДокументов)
v8_ExternalDataSource(ВнешнийИсточникДанных)
v8_HttpService(HTTPСервис)
v8_IntegrationService(СервисИнтеграции)
v8_Language(Язык)
v8_Report(Отчет)
v8_Style(Стиль)
v8_StyleItem(ЭлементСтиля)
v8_Subsystem(Подсистема)
v8_Task(Задача)
v8_WebService(ВебСервис)
v8_WsReference(ВебСсылка)
v8_XdtoPackage(ПакетXDTO)

v8_CommonModule(ОбщийМодуль)
v8_SessionParameter(ПараметрСеанса)

@enduml
