@startuml

!include dist/common.puml
' it is allowed to include all.puml - rather than an include per object.
' !include all.puml
!include dist/v8_Catalog.puml

title 1С:Enterprise icons for PlantUML

caption НСИ

package ТМЦ <<Rectangle>> #ffff99 {

    v8_Catalog(Номенклатура)
    Номенклатура : Ссылка

    v8_Catalog(ВидыНоменклатуры, "Виды номенклатуры")
    ВидыНоменклатуры : Ссылка

    v8_Catalog(одКлассыРентабельностиНоменклатуры, "Классы рентабельности номенклатуры")
    одКлассыРентабельностиНоменклатуры : Ссылка

}

package Взаиморасчеты <<Rectangle>> #b3c6ff {

    v8_Catalog(ДоговорыСКонтрагентами, "Договоры с контрагентами")
    ДоговорыСКонтрагентами : Ссылка
    ДоговорыСКонтрагентами : Контрагент

    v8_Catalog(Контрагенты)
    Контрагенты : Ссылка

}

ВидыНоменклатуры-->Номенклатура : Владелец
Номенклатура-->одКлассыРентабельностиНоменклатуры
Контрагенты-->ДоговорыСКонтрагентами

@enduml
