@startuml

!include ./dist/common.puml
' it is allowed to include all.puml - rather than an include per object.
' !include dist/all.puml
!include ./dist/v8_AccRg.puml
!include ./dist/v8_Document.puml
!include ./dist/v8_Catalog.puml
!include ./dist/v8_InfoRg.puml

title 1С:Enterprise icons for PlantUML

caption НСИ и документы

package ТМЦ <<Rectangle>> #ffff99 {

    _Справочник(Номенклатура)
    Номенклатура : Ссылка

    _Справочник(ВидыНоменклатуры, "Виды номенклатуры")
    ВидыНоменклатуры : Ссылка

    _Справочник(одКлассыРентабельностиНоменклатуры, "Классы рентабельности номенклатуры")
    одКлассыРентабельностиНоменклатуры : Ссылка

    _РегистрСведений(Ассортимент)

    _Документ(ПриобретениеТоваровУслуг, "Приобретение товаров и услуг")
    _Документ(ИзменениеАссортимента, "Изменение ассортимента")

    _РегистрНакопления(СвободныеОстатки, "Свободные остатки")

}

package Взаиморасчеты <<Rectangle>> #b3c6ff {

    _Справочник(ДоговорыСКонтрагентами, "Договоры с контрагентами")
    ДоговорыСКонтрагентами : Ссылка
    ДоговорыСКонтрагентами : Контрагент

    _Справочник(Контрагенты)
    Контрагенты : Ссылка

}

ВидыНоменклатуры-->Номенклатура : Владелец
Номенклатура-->одКлассыРентабельностиНоменклатуры
Контрагенты-->ДоговорыСКонтрагентами

ПриобретениеТоваровУслуг-down->СвободныеОстатки : "Приход"
ИзменениеАссортимента-down->Ассортимент

@enduml
