@startuml

!include dist/common.puml
' it is allowed to include all.puml - rather than an include per object.
' !include dist/all.puml
!include v8_AccRg.puml
!include v8_Document.puml
!include v8_Catalog.puml
!include v8_InfoRg.puml

title 1С:Enterprise icons for PlantUML

caption НСИ и документы

package ТМЦ <<Rectangle>> #ffff99 {

    v8_Catalog(Номенклатура)
    Номенклатура : Ссылка

    v8_Catalog(ВидыНоменклатуры, "Виды номенклатуры")
    ВидыНоменклатуры : Ссылка

    v8_Catalog(одКлассыРентабельностиНоменклатуры, "Классы рентабельности номенклатуры")
    одКлассыРентабельностиНоменклатуры : Ссылка

    v8_InfoRg(Ассортимент)

    v8_Document(ПриобретениеТоваровУслуг, "Приобретение товаров и услуг")
    v8_Document(ИзменениеАссортимента, "Изменение ассортимента")

    v8_AccRg(СвободныеОстатки, "Свободные остатки")

}

package Взаиморасчеты <<Rectangle>> #b3c6ff {

    v8_Catalog(ДоговорыСКонтрагентами, "Договоры с контрагентами")
    ДоговорыСКонтрагентами : Ссылка
    ДоговорыСКонтрагентами : Контрагент

    v8_Catalog(Контрагенты)
    Контрагенты : Ссылка

}

ВидыНоменклатуры-->Номенклатура : Владелец
Номенклатура-->одКлассыРентабельностиНоменклатуры
Контрагенты-->ДоговорыСКонтрагентами

ПриобретениеТоваровУслуг-down->СвободныеОстатки : "Приход"
ИзменениеАссортимента-down->Ассортимент

@enduml
